config/routes.rb
Rails.application.routes.draw do

  root :to => 'messages#index'

  resources :messages
  resources :issuing_scripts, only: :create

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inbox.rb
class Inbox < ApplicationRecord

  belongs_to :user
  has_many :messages

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :inbox
  belongs_to :outbox

  validates :body, presence: true
  scope :unread, -> { where(read: false) }

end

app/models/outbox.rb
class Outbox < ApplicationRecord

  belongs_to :user
  has_many :messages

end

app/models/payment.rb
class Payment < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  has_one :inbox
  has_one :outbox
  has_many :payments
  has_many :messages

  scope :patient, -> { where(is_patient: true) }
  scope :admin, -> { where(is_admin: true) }
  scope :doctor, -> { where(is_doctor: true) }

  def self.current
    User.patient.first
  end

  def self.default_admin
    User.admin.first
  end

  def self.default_doctor
    User.doctor.first
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/issuing_scripts_controller.rb
class IssuingScriptsController < ApplicationController
  def create
    IssuingScripts::Create.call

    redirect_to :messages, notice: 'Success.'
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = case params[:user_type]
                when 'Doctor'
                  User.default_doctor.inbox.messages.where(read: read).paginate(page: params[:page], per_page: 2)
                when 'Admin'
                  User.default_admin.inbox.messages.where(read: read).paginate(page: params[:page], per_page: 2)
                when 'Patient'
                  User.current.inbox.messages.where(read: read).paginate(page: params[:page], per_page: 2)
                else
                  Message.all.paginate(page: params[:page], per_page: 2)
                end
  end

  def show
    @message = Message.find(params[:id])
    @message.update(read: true)
    Inboxes::UpdateUnread.call(@message.inbox)
  end

  def new
    @message = Message.new
  end

  def create
    @message = Messages::Manual.new(message_params).call

    redirect_to :messages if @message
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def read
    params[:read] == 'Read'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issuing_scripts_helper.rb
module IssuingScriptsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NuaMessaging</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'navigation/header' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/index.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0">Search</h6>
  <%= form_tag("/messages", method: "get") do %>
    <%= select_tag(:user_type, options_for_select([['Patient'], ['Doctor'], ['Admin']], params[:user]), :prompt => 'Select User') %>
    <%= select_tag(:read, options_for_select([['Read'], ['Unread']], params[:status]), :prompt => 'Select Status') %>
    <%= submit_tag("Search") %>
  <% end %>
</div>

<div class="my-3 p-3 bg-white rounded shadow-sm">
<strong class="d-block text-gray-dark"><%="Doctorn Inbox, unread messages: #{User.default_doctor.inbox.unread}" if params[:user_type] == 'Doctor' %></strong>
<strong class="d-block text-gray-dark"><%='Admin Inbox' if params[:user_type] == 'Admin' %></strong>
<strong class="d-block text-gray-dark"><%='Patient Inbox' if params[:user_type] == 'Patient' %></strong>
<strong class="d-block text-gray-dark"><%='All messages' if params[:user_type] == '' %></strong>
<% @messages.each do |message| %>
  <%= link_to message do %>
    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark"><%= message.outbox.user.first_name %> <%= message.outbox.user.last_name %></strong>
        <%= message.body.truncate(45) %>
      </p>
    </div>
  <% end %>
<% end %>
<%= will_paginate @messages %>
</div>

</div>

app/views/messages/new.html.erb
<div class="card mt-3">
  <h5 class="card-header">
    New Message
  </h5>

  <div class="card-body">
    <%= form_for @message do |f| %>
      <div class="form-group py-3">
        <%= f.text_area :body, class: "form-control", rows: 3 %>
      </div>

      <div class="form-group mb-0 text-right">
        <%= f.submit 'Send Message', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

</div>

app/views/messages/show.html.erb
<div class="card my-3 ">
  <h5 class="card-header">
    <% if @message.outbox.user.is_doctor? %>Dr.<% end %>
    <%= @message.outbox.user.full_name %>
  </h5>
  <div class="card-body">
    <p class="card-text"><%= @message.body %></p>
    <% if @message.inbox.user.is_patient? %>
    <%= link_to "Reply", new_message_path, class: "btn btn-primary" %>
    <%= link_to "I've lost my script, charge me €10", issuing_scripts_path, method: :post, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/navigation/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Nua Messaging</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to messages_path, class: 'nav-link' do %>
          Inbox
        <% end  %>
      </li>
    </ul>
  </div>
</nav>